// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (name, age)
VALUES ($1, $2)
RETURNING id, name, age
`

type CreateUserParams struct {
	Name string
	Age  int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Age)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, age
FROM users
WHERE id= $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, age = $3
WHERE id = $1
RETURNING id, name, age
`

type UpdateUserParams struct {
	ID   int32
	Name string
	Age  int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Name, arg.Age)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}
